DROP TABLE IF EXISTS role;
CREATE TABLE role (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code VARCHAR(255),
  name VARCHAR(255)
);

DROP TABLE IF EXISTS user_role;
CREATE TABLE user_role (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  role_id INTEGER
);


