name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]
defaults:
  run:
    shell: bash
jobs:
  test:
    uses: ./.github/workflows/ci.yml
  build:
    if: ${{ github.event.pull_request.merged }} || ${{github.event.workflow_dispatch}}
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Maven Install
        run: mvn install -Dmaven.test.skip=true
      - name: Calculate Version
        id: version
        run: echo "::set-output name=version::$(date +%Y.%-m.%-d-%H%M%S)"
      - name: Build & Push Release Image
        run: |
          docker build . --tag cbidici/site:${{ steps.version.outputs.version }}
          docker push cbidici/site:${{ steps.version.outputs.version }}
          docker tag cbidici/site:${{ steps.version.outputs.version }} cbidici/site:latest
          docker push cbidici/site:latest
