name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]
defaults:
  run:
    shell: bash
jobs:
  build:
    if: ${{ github.event.pull_request.merged }} || ${{github.event.workflow_dispatch}}
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Calculate Version
        id: version
        run: echo "version=$(date +%Y.%-m.%-d-%H%M%S)"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set New Maven Version
        run: |
          mvn versions:set -DnewVersion=${{ steps.version.outputs.version }}
      - name: Maven Install
        run: mvn install -Dmaven.test.skip=true
      - name: Build & Push Release Image
        run: |
          docker build . --tag cbidici/${{ github.event.repository.name }}:${{ steps.version.outputs.version }} \
          --label author="${{ env.GIT_COMMIT_AUTHOR_NAME }}" \
          --label git_commit="${{ github.sha }}" \
          --label git_commit_short="${{ env.GIT_COMMIT_SHORT_SHA }}" \
          --label version="${{ steps.version.outputs.version }}" \
          --label repository="${{ github.event.repository.name }}"
          docker push cbidici/${{ github.event.repository.name }}:${{ steps.version.outputs.version }}
