name: CI
on:
  workflow_dispatch:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
      - 'closed'
      - 'synchronize'
permissions:
  checks: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile
        run: mvn clean compile test-compile
      - name: Run Unit Tests
        run: mvn test -P unit
      - name: Run Integration Tests
        run: mvn test -P integration
      - name: Report
        uses: mikepenz/action-junit-report@v3
        if: ${{ always() }}
        with:
          report_paths: '**/target/surefire-reports/*.xml'
